version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/Logistic_Model.pkl
      - LOG_LEVEL=info
    volumes:
      - ./models:/app/models
      - ./dataset:/app/dataset
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 